settings creation changes

diff --git a/examples/cicd-argocd/seldon-core/install-helm b/examples/cicd-argocd/seldon-core/install-helm
--- a/examples/cicd-argocd/seldon-core/install-helm
+++ b/examples/cicd-argocd/seldon-core/install-helm
@@ -7,7 +7,8 @@ set -o pipefail
 STARTUP_DIR="$( cd "$( dirname "$0" )" && pwd )"
 
 if [ ! -f "${STARTUP_DIR}/../settings.sh" ]; then
-    cp -v "${STARTUP_DIR}/../settings.sh.example" "${STARTUP_DIR}/../settings.sh"
+    echo "settings.sh not found!"
+    exit 1
 fi
 source ${STARTUP_DIR}/../settings.sh
 
