update builder script for python

diff --git a/wrappers/s2i/python/s2i/bin/assemble b/wrappers/s2i/python/s2i/bin/assemble
--- a/wrappers/s2i/python/s2i/bin/assemble
+++ b/wrappers/s2i/python/s2i/bin/assemble
@@ -7,10 +7,36 @@
 #	https://github.com/openshift/source-to-image/blob/master/docs/builder_image.md
 #
 
-# If the 'seldon-core-s2i-python' assemble script is executed with the '-h' flag, print the usage.
+# If the 'seldon-core-s2i-python2' assemble script is executed with the '-h' flag, print the usage.
 if [[ "$1" == "-h" ]]; then
 	exec /usr/libexec/s2i/usage
 fi
+
+
+if [[ -z "$MODEL_NAME" ]]; then
+
+    echo "Failed to find required env var MODEL_NAME"
+    exit 1
+fi
+
+if [[ -z "$API_TYPE" ]]; then
+
+    echo "Failed to find required env var API_TYPE, should be either REST or GRPC."
+    exit 1
+fi
+
+if [[ -z "$SERVICE_TYPE" ]]; then
+
+    echo "Failed to find required env var SERVICE_TYPE, should be one of MODEL, ROUTER, TRANSFORMER, COMBINER."
+    exit 1
+fi
+
+if [[ -z "$PERSISTENCE" ]]; then
+
+    echo "Failed to find required env var PERSISTENCE, should be 0 or 1."
+    exit 1
+fi
+
 
 cd /microservice
 
