merge conda and regular python s2i wrappers, closes #1125

diff --git a/wrappers/s2i/python/s2i/bin/run b/wrappers/s2i/python/s2i/bin/run
--- a/wrappers/s2i/python/s2i/bin/run
+++ b/wrappers/s2i/python/s2i/bin/run
@@ -7,6 +7,20 @@
 #	https://github.com/openshift/source-to-image/blob/master/docs/builder_image.md
 #
 
+function _get_conda_envs() {
+    # Printed value will be list of Conda envs
+    conda env list | tail -n +3 | head -n -1 | cut -d' ' -f1
+}
+
+function _is_env_present() {
+    # $1 is the Conda env we are probing
+    # Return value will be 0 if present (TRUE)
+
+    local _conda_envs=$(_get_conda_envs)
+    echo $_conda_envs | grep -qw $1
+    return $?
+}
+
 #check environment vars
 if [[ -z "$MODEL_NAME" || -z "$API_TYPE" || -z "$SERVICE_TYPE" || -z "$PERSISTENCE" ]]; then
 
@@ -15,8 +29,21 @@ if [[ -z "$MODEL_NAME" || -z "$API_TYPE" || -z "$SERVICE_TYPE" || -z "$PERSISTEN
 
 else
     cd /microservice
+
+    if [[ -x before-run ]]; then
+        echo "Executing before-run script"
+        ./before-run
+    fi
+
+    CONDA_ENV_NAME=${CONDA_ENV_NAME:-microservice}
+    if _is_env_present $CONDA_ENV_NAME; then
+        echo "Activating Conda environment '$CONDA_ENV_NAME'"
+        # We need to initialise Conda so that it can run on /bin/sh
+        source /etc/profile.d/conda.sh
+        conda activate $CONDA_ENV_NAME
+    fi
+
     echo "starting microservice"
     exec seldon-core-microservice $MODEL_NAME $API_TYPE --service-type $SERVICE_TYPE --persistence $PERSISTENCE
 
 fi
-
