check scan results and scan conda image

diff --git a/.github/workflows/security_tests_v1.yml b/.github/workflows/security_tests_v1.yml
--- a/.github/workflows/security_tests_v1.yml
+++ b/.github/workflows/security_tests_v1.yml
@@ -100,6 +100,16 @@ jobs:
       with:
         name: conda-image
         path: /tmp/conda-image.tar
+    - name: Scan Conda image
+      id: scan-conda
+      uses: snyk/actions/docker@master
+      continue-on-error: true
+      env:
+        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+      with:
+        image: ${{ env.CONDA_BASE_IMAGE}}:test
+        args:  --app-vulns --severity-threshold=high --file=wrappers/s2i/python/Dockerfile.conda
+
     - name: Build (Base Wrapper)
       working-directory: ./wrappers/s2i/python
       run: |
@@ -111,6 +121,7 @@ jobs:
         name: python-base-image
         path: /tmp/python-base-image.tar
     - name: Scan Python base image
+      id: scan-python-base
       uses: snyk/actions/docker@master
       continue-on-error: true
       env:
@@ -135,6 +146,7 @@ jobs:
         echo "SKLEARN_IMAGE_TAG=$SKLEARN_IMAGE_TAG" >> $GITHUB_ENV
         make IMAGE_NAME=$SKLEARN_IMAGE_TAG VERSION=test BASE_IMAGE=${{ env.PYTHON_BASE_IMAGE}}:test docker-build
     - name: Scan sklearn
+      id: scan-sklearn
       if: steps.build-sklearn.outcome == 'success'
       uses: snyk/actions/docker@master
       continue-on-error: true
@@ -157,6 +169,7 @@ jobs:
         echo "MLFLOW_IMAGE_TAG=$MLFLOW_IMAGE_TAG" >> $GITHUB_ENV
         make IMAGE_NAME=$MLFLOW_IMAGE_TAG VERSION=test BASE_IMAGE=${{ env.PYTHON_BASE_IMAGE}}:test docker-build
     - name: Scan mlflow
+      id: scan-mlflow
       if: steps.build-mlflow.outcome == 'success'
       uses: snyk/actions/docker@master
       continue-on-error: true
@@ -180,6 +193,7 @@ jobs:
         echo "XGBOOST_IMAGE_TAG=$XGBOOST_IMAGE_TAG" >> $GITHUB_ENV
         make IMAGE_NAME=$XGBOOST_IMAGE_TAG VERSION=test BASE_IMAGE=${{ env.PYTHON_BASE_IMAGE}}:test docker-build
     - name: Scan xgboost
+      id: scan-xgboost
       if: steps.build-xgboost.outcome == 'success'
       uses: snyk/actions/docker@master
       continue-on-error: true
@@ -202,6 +216,7 @@ jobs:
         echo "ALIBI_EXPLAIN_IMAGE_TAG=$ALIBI_EXPLAIN_IMAGE_TAG" >> $GITHUB_ENV
         make IMAGE=$ALIBI_EXPLAIN_IMAGE_TAG VERSION=test BASE_IMAGE=${{ env.PYTHON_BASE_IMAGE}} docker-build
     - name: Scan alibi explain
+      id: scan-alibi-explain
       if: steps.build-alibi-explain.outcome == 'success'
       uses: snyk/actions/docker@master
       continue-on-error: true
@@ -216,23 +231,39 @@ jobs:
       if: always()
       run: docker rmi ${{ env.ALIBI_EXPLAIN_IMAGE_TAG}}:test
 
-    - name: Build (alibi detect)
-      id: build-alibi-detect
-      continue-on-error: true
-      working-directory: ./components/alibi-detect-server
+
+    - name: Check for image scan failures
+      if: always()
       run: |
-        export ALIBI_DETECT_IMAGE_TAG="sec-tests/alibi-detect-$(date +%s)-$(openssl rand -hex 4)"
-        echo "ALIBI_DETECT_IMAGE_TAG=$ALIBI_DETECT_IMAGE_TAG" >> $GITHUB_ENV
-        make IMAGE=$ALIBI_DETECT_IMAGE_TAG VERSION=test BASE_IMAGE=${{ env.PYTHON_BASE_IMAGE}} docker-build
-    - name: Scan alibi detect
-      if: steps.build-alibi-detect.outcome == 'success'
-      uses: snyk/actions/docker@master
-      continue-on-error: true
-      env:
-        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
-      with:
-        image: ${{ env.ALIBI_DETECT_IMAGE_TAG}}:test
-        args:  --fail-on=upgradable --app-vulns --severity-threshold=high --file=components/alibi-detect-server/Dockerfile
+        if [ "${{ steps.scan-alibi-explain.outcome }}" != "success" ] || \
+           [ "${{ steps.scan-xgboost.outcome }}" != "success" ] || \
+           [ "${{ steps.scan-sklearn.outcome }}" != "success" ] || \
+           [ "${{ steps.scan-python-base.outcome }}" != "success" ] || \
+           [ "${{ steps.scan-conda.outcome }}" != "success" ] || \
+           [ "${{ steps.scan-mlflow.outcome }}" != "success" ]; then
+          echo "One or more docker image scans did not succeed"
+          exit 1
+        fi
+
+# TODO had to comment out due to GH runner out of disk space, image can be built locally if needed, or may have to use
+#  own runner
+#    - name: Build (alibi detect)
+#      id: build-alibi-detect
+#      continue-on-error: true
+#      working-directory: ./components/alibi-detect-server
+#      run: |
+#        export ALIBI_DETECT_IMAGE_TAG="sec-tests/alibi-detect-$(date +%s)-$(openssl rand -hex 4)"
+#        echo "ALIBI_DETECT_IMAGE_TAG=$ALIBI_DETECT_IMAGE_TAG" >> $GITHUB_ENV
+#        make IMAGE=$ALIBI_DETECT_IMAGE_TAG VERSION=test BASE_IMAGE=${{ env.PYTHON_BASE_IMAGE}} docker-build
+#    - name: Scan alibi detect
+#      if: steps.build-alibi-detect.outcome == 'success'
+#      uses: snyk/actions/docker@master
+#      continue-on-error: true
+#      env:
+#        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+#      with:
+#        image: ${{ env.ALIBI_DETECT_IMAGE_TAG}}:test
+#        args:  --fail-on=upgradable --app-vulns --severity-threshold=high --file=components/alibi-detect-server/Dockerfile
 
   security-image-initializer-rclone:
     runs-on: ubuntu-latest
@@ -245,7 +276,6 @@ jobs:
         echo "RCLONE_IMAGE_TAG=$RCLONE_IMAGE_TAG" >> $GITHUB_ENV
         make IMAGE_TAG=$RCLONE_IMAGE_TAG docker-build
     - name: Scan rclone
-      continue-on-error: false
       uses: snyk/actions/docker@master
       env:
         SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
